analytics: {}
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.73014
  lightness: 0.928827
  rhythmicContrast: 0.776617
  saturation: 0.384022
cta: {}
layout_spectrum: 0.29535219448079675
name: niekt
opengraph: {}
purpose: {}
typography_spectrum: 0.332207
